#!/usr/bin/env bash
# Script that prints Best School 10 times but prints hi on the 9th iteration


i=1

while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
		((i++))
done
